/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PulsesViewer: typeof import('./src/modules/PulsesViewer/index.vue')['default']
    PulsesViewItem: typeof import('./src/modules/PulsesViewer/components/PulsesViewItem.vue')['default']
    PulsesViewMeasurementsDecoders: typeof import('./src/modules/PulsesViewer/components/PulsesViewMeasurementsDecoders.vue')['default']
    PulsesViewMeasurementsRects: typeof import('./src/modules/PulsesViewer/components/PulsesViewMeasurementsRects.vue')['default']
    PulsesViewRoot: typeof import('./src/modules/PulsesViewer/components/PulsesViewRoot.vue')['default']
    PulsesViewSessionSelecotr: typeof import('./src/modules/PulsesViewer/components/PulsesViewSessionSelecotr.vue')['default']
    PulsesViewSVGHelpers: typeof import('./src/modules/PulsesViewer/components/PulsesViewSVGHelpers.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
